/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef MELODI_UAPI_H
#define MELODI_UAPI_H

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <stdint.h>
#endif

#define MELODI_GENL_NAME "melodi"
#define MELODI_GENL_VERSION 1
#define MELODI_NODE_ID_SIZE 33
#define MELODI_NODE_KEY_SIZE 32
#define MELODI_NODE_ID_SCHEME_ED25519 1
#define MELODI_NODE_ID_TEXT_SIZE 54
#define MELODI_NODE_ID_STRING_SIZE 55
#define MELODI_MESSAGE_MTU 4096
#define MELODI_BROADCAST_MTU 512
#define MELODI_FRAME_MTU_MAX (MELODI_MESSAGE_MTU + 80)
#define MELODI_FRAME_HEADER_MIN 40
#define MELODI_SERVICE_CONTROL 0
#define MELODI_SERVICE_ECHO 65535
#define MELODI_PRIORITY_MAX 3
#define MELODI_TTL_DEFAULT_MS 30000
#define MELODI_RADIO_SERIAL_MAX 63
#define MELODI_BUS_INFO_MAX 31

enum melodi_command {
    MELODI_CMD_UNSPEC,
    MELODI_CMD_BIND,
    MELODI_CMD_UNBIND,
    MELODI_CMD_SEND,
    MELODI_CMD_RECV,
    MELODI_CMD_ERROR,
    MELODI_CMD_GET_BINDING,
    MELODI_CMD_LINK_GET = 32,
    MELODI_CMD_LINK_SET,
    MELODI_CMD_IDENTITY_LOAD,
    MELODI_CMD_IDENTITY_GET_PUBLIC,
    MELODI_CMD_PEER_DUMP,
    MELODI_CMD_PEER_TRUST,
    MELODI_CMD_PEER_BLOCK,
    MELODI_CMD_PEER_CLEAR,
    MELODI_CMD_PEER_REVERIFY,
    MELODI_CMD_DISCOVER,
    MELODI_CMD_POLICY_GET,
    MELODI_CMD_POLICY_SET,
    MELODI_CMD_STATS_GET,
    MELODI_CMD_MONITOR_BIND,
    MELODI_CMD_MONITOR_FRAME,
};

enum melodi_attribute {
    MELODI_A_UNSPEC,
    MELODI_A_IFINDEX,
    MELODI_A_LOCAL_SERVICE,
    MELODI_A_DEST_NODE,
    MELODI_A_DEST_SERVICE,
    MELODI_A_SOURCE_NODE,
    MELODI_A_SOURCE_SERVICE,
    MELODI_A_PAYLOAD,
    MELODI_A_FLAGS,
    MELODI_A_COOKIE,
    MELODI_A_TTL_MS,
    MELODI_A_PRIORITY,
    MELODI_A_RX_META,
    MELODI_A_ERROR,
    MELODI_A_NODE_ID,
    MELODI_A_KEY_SERIAL,
    MELODI_A_LINK_STATE,
    MELODI_A_PEER_NATIVE_LOCATOR,
    MELODI_A_COLLISION_ROUND,
    MELODI_A_PEER_STATE,
    MELODI_A_GENERATION,
    MELODI_A_POLICY_MODE,
    MELODI_A_LINK_FAILURE,
    MELODI_A_LINK_ERROR,
    MELODI_A_RADIO_SERIAL,
    MELODI_A_STATS,
    MELODI_A_MONITOR_DIRECTION,
    MELODI_A_FRAME,
    MELODI_A_BUS_INFO,
    MELODI_A_PREVIOUS_NODE_ID,
    MELODI_A_POLICY_SERVICE,
    MELODI_A_POLICY_ACTION,
    MELODI_A_POLICY_BROADCAST,
    MELODI_A_PEER_EXPIRY_MS,
    MELODI_A_PEER_CAPABILITIES,
    MELODI_A_PEER_RSSI,
    MELODI_A_PEER_SNR,
    MELODI_A_PEER_HOPS,
    MELODI_A_PEER_LAST_SEEN_NS,
    MELODI_A_PEER_POLICY,
    MELODI_A_POLICY_RESET,
    __MELODI_A_MAX,
};

#define MELODI_A_MAX (__MELODI_A_MAX - 1)

enum melodi_rx_meta_attribute {
    MELODI_RX_A_UNSPEC,
    MELODI_RX_A_AUTHENTICATED,
    MELODI_RX_A_DUPLICATES,
    MELODI_RX_A_HOPS,
    MELODI_RX_A_RSSI,
    MELODI_RX_A_SNR,
    MELODI_RX_A_TIMESTAMP_NS,
    MELODI_RX_A_RETRANSMISSIONS,
    __MELODI_RX_A_MAX,
};

#define MELODI_RX_A_MAX (__MELODI_RX_A_MAX - 1)

enum melodi_error_attribute {
    MELODI_ERROR_A_UNSPEC,
    MELODI_ERROR_A_CODE,
    MELODI_ERROR_A_DETAIL,
    __MELODI_ERROR_A_MAX,
};

#define MELODI_ERROR_A_MAX (__MELODI_ERROR_A_MAX - 1)

enum melodi_stat_attribute {
    MELODI_STAT_A_UNSPEC,
    MELODI_STAT_A_RX_PACKETS,
    MELODI_STAT_A_RX_BYTES,
    MELODI_STAT_A_RX_ERRORS,
    MELODI_STAT_A_RX_DROPPED,
    MELODI_STAT_A_TX_PACKETS,
    MELODI_STAT_A_TX_BYTES,
    MELODI_STAT_A_TX_ERRORS,
    MELODI_STAT_A_TX_DROPPED,
    MELODI_STAT_A_TX_QUEUE_FRAMES,
    MELODI_STAT_A_TX_QUEUE_BYTES,
    MELODI_STAT_A_AUTHENTICATED_PEERS,
    MELODI_STAT_A_REASSEMBLIES,
    MELODI_STAT_A_RELIABLE_PENDING,
    MELODI_STAT_A_DISCOVERY_PENDING,
    MELODI_STAT_A_AUTH_FAILURES,
    MELODI_STAT_A_REPLAY_DROPS,
    MELODI_STAT_A_BROADCAST_TX,
    MELODI_STAT_A_BROADCAST_RX,
    MELODI_STAT_A_AIRTIME_US,
    MELODI_STAT_A_BROADCAST_AIRTIME_US,
    MELODI_STAT_A_DUTY_DEFERS,
    MELODI_STAT_A_QUEUE_EXPIRED,
    MELODI_STAT_A_APP_DELIVERY_DROPS,
    MELODI_STAT_A_MONITOR_DROPS,
    __MELODI_STAT_A_MAX,
};

#define MELODI_STAT_A_MAX (__MELODI_STAT_A_MAX - 1)

enum melodi_monitor_direction {
    MELODI_MONITOR_RX,
    MELODI_MONITOR_TX,
};

enum melodi_send_flag {
    MELODI_F_RELIABLE = 1U << 0,
    MELODI_F_ORDERED = 1U << 1,
    MELODI_F_AUTH_REQUIRED = 1U << 2,
    MELODI_F_BROADCAST = 1U << 3,
    MELODI_F_DONTWAIT = 1U << 4,
};

enum melodi_link_state {
    MELODI_LINK_DISCONNECTED,
    MELODI_LINK_CONFIGURING,
    MELODI_LINK_READY,
    MELODI_LINK_FAILED,
};

enum melodi_link_failure {
    MELODI_LINK_FAILURE_NONE,
    MELODI_LINK_FAILURE_TRANSPORT,
    MELODI_LINK_FAILURE_STREAM,
    MELODI_LINK_FAILURE_PROTOBUF,
    MELODI_LINK_FAILURE_FIRMWARE,
    MELODI_LINK_FAILURE_REGION,
    MELODI_LINK_FAILURE_MODEM,
    MELODI_LINK_FAILURE_HOP_LIMIT,
    MELODI_LINK_FAILURE_RADIO_TX,
    MELODI_LINK_FAILURE_MQTT,
    MELODI_LINK_FAILURE_CHANNEL,
    MELODI_LINK_FAILURE_CONFIG_NONCE,
    MELODI_LINK_FAILURE_NODE_NUMBER,
    MELODI_LINK_FAILURE_PRIVATE_PORT,
    MELODI_LINK_FAILURE_PAYLOAD_BUDGET,
    MELODI_LINK_FAILURE_QUEUE_STATUS,
    MELODI_LINK_FAILURE_ROUTING_RESULTS,
    MELODI_LINK_FAILURE_TIMEOUT,
    MELODI_LINK_FAILURE_INTERNAL,
    __MELODI_LINK_FAILURE_MAX,
};

#define MELODI_LINK_FAILURE_MAX (__MELODI_LINK_FAILURE_MAX - 1)

enum melodi_peer_state {
    MELODI_PEER_AUTHENTICATED,
    MELODI_PEER_TRUSTED,
    MELODI_PEER_BLOCKED,
    MELODI_PEER_CONFLICTED,
    MELODI_PEER_OBSERVED,
    MELODI_PEER_CHALLENGED,
};

enum melodi_policy_mode {
    MELODI_POLICY_ALLOW_AUTHENTICATED,
    MELODI_POLICY_REQUIRE_TRUST,
};

enum melodi_peer_policy {
    MELODI_PEER_POLICY_DEFAULT,
    MELODI_PEER_POLICY_TRUSTED,
    MELODI_PEER_POLICY_BLOCKED,
};

enum melodi_policy_action {
    MELODI_POLICY_SERVICE_ALLOW = 1,
    MELODI_POLICY_SERVICE_DENY,
    MELODI_POLICY_SERVICE_CLEAR,
};

#define MELODI_F_ALL (MELODI_F_RELIABLE | MELODI_F_ORDERED | \
                      MELODI_F_AUTH_REQUIRED | MELODI_F_BROADCAST | \
                      MELODI_F_DONTWAIT)

struct melodi_node_id {
#ifdef __KERNEL__
    __u8 bytes[MELODI_NODE_ID_SIZE];
#else
    uint8_t bytes[MELODI_NODE_ID_SIZE];
#endif
};

#endif
